
version: "3"
services:

    app:
        build: ./app
        env_file: 
            - .env
        depends_on:
            - db
        ports:
            - "5000:5000"
        restart: always


      
    db:
        restart: always
        container_name: "postgresql"
        image: postgres
        ports:
            - "5433:5433"
        
        environment:
            POSTGRES_PASSWORD: "superUser123"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "postgres"
            



