
version: "3"
services:

    jenkins: 
        image: jenkins/jenkins
        user: "root"
        volumes: 
            - ./jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            docker-compose: "/usr/local/bin/docker-compose"
        ports: 
            - "8080:8080"

    app:
        build: app
        env_file: 
            - .env
        depends_on:
            - db
        ports:
            - "5000:5000"
        restart: always


      
    db:
        restart: always
        container_name: "postgresql"
        image: postgres
        ports:
            - "5432:5432"
        
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "postgres"
            



