From postgres
ENV POSTGRES_PASSWORD: "root"
ENV POSTGRES_USER: "postgres"
ENV POSTGRES_DB: "postgres"

# COPY pg_hba.conf      /tmp/pg_hba.conf
# COPY updateConfig.sh      /docker-entrypoint-initdb.d/_updateConfig.sh
COPY pg_hba.conf /etc/postgresql
# RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/10/main/pg_hba.conf
# RUN echo "listen_addresses='*'" >> /etc/postgresql/10/main/postgresql.conf
EXPOSE 5432

CMD ["postgres", "-c", "config_file=/etc/postgresql/pg_hba.conf"]

