
version: "3"
services:

    jenkins: 
        image: jenkinsci/blueocean
        user: "root"
        # https://stackoverflow.com/questions/38105308/jenkins-cant-connect-to-docker-daemon
        volumes: 
            - ./jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            # - ./:/home
        ports: 
            - "8080:8080"

    app:
        build: ./ressource
        env_file: 
            - .env
        depends_on:
            - db
        ports:
            - "5000:5000"
        restart: always


      
    db:
        restart: always
        container_name: "postgresql"
        image: postgres
        ports:
            - "5433:5433"
        
        environment:
            POSTGRES_PASSWORD: "superUser123"
            POSTGRES_USER: "postgres"
            POSTGRES_DB: "postgres"
            



